- name: install Nginx
  hosts: shell
  become: yes
  tasks:
    - name: install Nginx using package
      ansible.builtin.package:
        name: nginx
        state: present

    - name: start Nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
