- name: filters in ansible
  hosts: local
  connection: local
  vars:
    Topics: Linux, Ansible, Terraform, Docker, Kubernetes
    course: "Devops with AWS"
    Details:
      name: "Ashish"
      Domian: "Devops"
      Branch: "CSE"
      Pursuing: "B.Tech"
    TagsList:
        [
          {'key': 'name', 'value': 'Ashish'},
          {'key': 'Domian', 'value': 'Devops'}, 
          {'key': 'Branch', 'value': 'CSE'}, 
          {'key': 'Pursuing', 'value': 'B.Tech'}
        ]

  tasks:
    - name: ansible filters
      ansible.builtin.debug:
       msg: "Congratulations  {{ Greeting | default('Ashish')  }}"
      
    - name: Split the string  into a list
      ansible.builtin.debug:
       msg: "Topics are {{ Topics | split(',') }}"

    - name: Convert Map to list
      ansible.builtin.debug:
       msg: "Details are {{ Details | dict2items }}"
   
    - name: Convert list to Map
      ansible.builtin.debug:
       msg: "TagLists are {{ TagsList | items2dict }}"

    - name: Convert string to Lowercase
      ansible.builtin.debug:
       msg: "Course name is {{ course | lower }}"

    - name: Convert String to UpperCase
      ansible.builtin.debug:
       msg: "Course name is {{ course | upper }}"
       
    - name: Convert String to Title Case
      ansible.builtin.debug:
       msg: "Course name is {{ course | title }}"