- name: error handling in ansible
  hosts: local
  connection: local
  vars:
   num1: 10
   num2: 0
  tasks:
   - name: division of two numbers
     ansible.builtin.debug:
       msg: "Result: {{ num1 / num2}}" 
     ignore_errors: true

   - name: check user exits  or not
     ansible.builtin.command: id catalyst
     register: out_put
     ignore_errors: true

   - name: print the output
     ansible.builtin.debug:
      msg: "User doesnot exit {{ out_put }}"
     when: out_put.rc != 0
  
   - name: create user if not exits 
     ansible.builtin.user:
       name: catalyst
       state: present
    